apiVersion: v2
name: mlflow-tracking-server
description: A Helm chart for MlFlow Tracking Server
icon: https://raw.githubusercontent.com/mlflow/mlflow/master/assets/logo.svg
type: application
version: 2.0.0
appVersion: "6.3.0"
home: https://github.com/mlflow-oidc/helm
sources:
  - https://github.com/mlflow-oidc/helm
  - https://github.com/mlflow-oidc/mlflow-tracking-server-docker
maintainers:
  - email: alex@kharkevich.org
    name: Alexander Kharkevich

dependencies:
  - name: common
    repository: https://technicaldomain.github.io/helm/
    version: 2.1.5
