{{- template "common.configmap" (list . "application.env_configmap") -}}
{{- define "application.env_configmap" -}}
data:
  {{- with .Values.config.data }}
  {{- range $key, $value := . }}
  {{ $key | upper }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end -}}
